<script lang="ts">
	/**
	 * Where an owner starts.
	 *
	 * A pasted token rather than a password, because there is no account system and inventing one
	 * badly would be worse than not having one. The token is generated by
	 * `sahl-server issue-dashboard-token`, has real entropy, and is revocable — which a four-digit
	 * till PIN on a public endpoint would not be.
	 */
	import { Button, Card, Field, Input } from '@sahl/ui';
	import { enhance } from '$app/forms';

	let { form } = $props();
	let token = $state('');
</script>

<svelte:head><title>Sign in · Sahl</title></svelte:head>

<main class="bg-canvas text-text density-compact flex min-h-dvh items-center justify-center p-6">
	<Card label="Sahl" class="w-full max-w-md">
		<form method="POST" use:enhance class="flex flex-col gap-4">
			<div>
				<h1 class="text-lg font-semibold">Your shop, from here</h1>
				<p class="text-secondary text-text-secondary mt-1">
					Paste the access token from your terminal's operator. It is not your till PIN — a PIN is
					four digits, which is fine at a counter and not fine on the internet.
				</p>
			</div>

			<Field id="token" label="Access token">
				{#snippet children({ id, describedBy })}
					<Input {id} {describedBy} bind:value={token} numeric forceLtr placeholder="paste here" />
				{/snippet}
			</Field>

			<input type="hidden" name="token" value={token} />

			{#if form?.message}
				<p class="text-secondary text-danger-text" role="alert">{form.message}</p>
			{/if}

			<Button variant="primary" size="lg" block type="submit">Sign in</Button>
		</form>
	</Card>
</main>
